### ISSUE TITLE
Cut new tag and publish to npmjs

### ISSUE THREAD

**Issue by InAnimaTe** [lifted-studios/hubot-github-event-announcer#18]
plzzzzzz!

I'd really like that fix to go in so I can stably use this with hubot/rocketchat ;)

Thanks a lot for this awesome plugin. As we use it more, we may have more pr's to make it better!

**Comment by lee-dohm** [comment]
I'm working on it ... give me a few minutes :wink:

**Comment by InAnimaTe** [comment]
hehe, thx a lot!

**Comment by lee-dohm** [comment]
Done!
